### ISSUE TITLE
`Discourse.topic_url_valid` is too fussy

### ISSUE THREAD

**Issue by barrettj12** [canonical/upload-charm-docs#40]
In `discourse.py` there is a method which checks if Discourse URLs are valid:
https://github.com/canonical/upload-charm-docs/blob/bdaf92b7d6f42b95be3ede01596ec55985a1b4cc/src/discourse.py#L86

A Discourse URL must have the form `/t/topic-slug/<id-num>` to pass validation here, e.g.
https://discourse.charmhub.io/t/get-started-with-the-juju-olm/6559

However, either the slug or topic ID can be omitted, as it can be deduced from the other one. e.g.
https://discourse.charmhub.io/t/6559
https://discourse.charmhub.io/t/get-started-with-the-juju-olm
are both valid URLs, redirecting to the first URL.

This is causing the action to fail when trying to migrate our docs to GitHub. The navigation table contains a link to `/t/6559`, which is failing validation, raising an exception and causing the action to fail.

I would question the need for URL validation at all. When migrating, we should assume that the URLs provided on Discourse are valid, since they already work for existing docs. If a URL really is invalid, then this will be caught later when trying to make a request to it.

**Comment by jdkandersson** [comment]
Makes sense, maybe instead of complaining the action should try to resolve the URL and fix it up. If that fails, it can complain. How does that sound?

**Comment by jdkandersson** [comment]
Also, the migration currently has a bug #41 which we're working to resolve

**Comment by barrettj12** [comment]
> Makes sense, maybe instead of complaining the action should try to resolve the URL and fix it up. If that fails, it can complain. How does that sound?

Better, but that would still result in extra (unnecessary?) API calls.

IINM, the `Discourse.topic_url_valid` method is only used in `Discourse._url_to_topic_info`:
https://github.com/canonical/upload-charm-docs/blob/bdaf92b7d6f42b95be3ede01596ec55985a1b4cc/src/discourse.py#L140

to try and retrieve "topic info" (slug and topic ID). But I'm not sure if **both** the slug **and** topic ID are really necessary. Discourse seems to be happy with just one of them.

**Comment by jdkandersson** [comment]
The API call is quite useful because the user will be alerted much earlier that there is a problem with the URL rather than having to wait until that URL is retrieved which will result in an error later. 

It is important that the URLs have both the slug and topic id when they are handled because things like the path in the navigation table depend on reading the path. With the PR, the action will now automatically fix up any URLs that have either the topic id or the slug missing. If there is a significant performance impact, we can consider making changes to only require the HEAD request, for example, if the slug or topic id is missing.
